export const CONDITIONS = [
  {
    id: "chemotherapy",
    label: "Chemotherapy",
    icon: "🧪",
    description: "For reduced taste sensitivity",
    gradient: "from-red-500 to-pink-500",
    color: "text-red-600",
    glow: "shadow-red-500/50",
    hoverGlow: "hover:shadow-red-500/70",
  },
  {
    id: "senior",
    label: "Senior (65+)",
    icon: "👵",
    description: "For age-related taste loss",
    gradient: "from-blue-500 to-indigo-500",
    color: "text-blue-600",
    glow: "shadow-blue-500/50",
    hoverGlow: "hover:shadow-blue-500/70",
  },
  {
    id: "diabetic",
    label: "Diabetic",
    icon: "🍭",
    description: "For sugar-conscious eating",
    gradient: "from-green-500 to-emerald-500",
    color: "text-green-600",
    glow: "shadow-green-500/50",
    hoverGlow: "hover:shadow-green-500/70",
  },
  {
    id: "low-sodium",
    label: "Low Sodium",
    icon: "🧂",
    description: "For hypertension management",
    gradient: "from-yellow-500 to-amber-500",
    color: "text-yellow-600",
    glow: "shadow-yellow-500/50",
    hoverGlow: "hover:shadow-yellow-500/70",
  },
  {
    id: "post-covid",
    label: "Post-COVID",
    icon: "👃",
    description: "For smell distortion recovery",
    gradient: "from-purple-500 to-violet-500",
    color: "text-purple-600",
    glow: "shadow-purple-500/50",
    hoverGlow: "hover:shadow-purple-500/70",
  },
];
